@authToken =
@title =
@order =
@boardId =
@id =

PUT http://localhost:3000/column
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "id": {{id}},
  "title": "{{title}}",
  "order": {{order}},
  "boardId": "{{boardId}}"
}
